version: '3.8'

services:
  playlist-service:
    build: .
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      - GRPC_HOST=${GRPC_HOST}
      - GRPC_PORT=${GRPC_PORT}
    depends_on:
      - playlist-service-postgres

  playlist-service-postgres:
    image: postgres
    container_name: playlist-service-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  playlist-service-prometheus:
    image: prom/prometheus
    container_name: playlist-service-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  playlist-service-grafana:
    image: grafana/grafana
    container_name: playlist-service-grafana
    restart: always
    ports:
      - "3000:3000"