global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: grpc_service
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8082'